apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-frontend
  namespace: ai-task-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-frontend
  template:
    metadata:
      labels:
        app: ai-frontend
    spec:
      containers:
      - name: ai-frontend
        image: sidharth0307/ai-frontend:c6d88db90f7e603d3cbe4bb65136592ccfcf897d
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5