apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-worker
  namespace: ai-task-platform
spec:
  # Worker should support scaling to multiple replicas
  replicas: 3 
  selector:
    matchLabels:
      app: ai-worker
  template:
    metadata:
      labels:
        app: ai-worker
    spec:
      containers:
      - name: ai-worker
        image: sidharth0307/ai-worker:c6d88db90f7e603d3cbe4bb65136592ccfcf897d
        envFrom:
        - configMapRef:
            name: ai-configmap
        - secretRef:
            name: ai-secrets
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "500m"